// Copyright NaviSyn Marine Solutions. NaviSense_UE5 primary runtime module.
// Generated by the NaviSense remote-prep automation (Phase 1 of the Master Guide).

using UnrealBuildTool;
using System.IO;

public class NaviSense : ModuleRules
{
    public NaviSense(ReadOnlyTargetRules Target) : base(Target)
    {
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

        // Headers live directly under the module root in subfolders (Core/, Bridge/,
        // Vessel/, Sensors/). Add the module dir as an include base so path-qualified
        // includes like "Bridge/NaviSenseBridgeTypes.h" resolve from any .cpp/.h.
        PublicIncludePaths.Add(ModuleDirectory);
        PrivateIncludePaths.Add(ModuleDirectory);

        // Core engine + the modules the NaviSense stack needs across phases.
        PublicDependencyModuleNames.AddRange(new string[]
        {
            "Core",
            "CoreUObject",
            "Engine",
            "InputCore",
            "Json",           // bridge DTO (de)serialization
            "JsonUtilities",  // FJsonObjectConverter <-> USTRUCT
            "Sockets",        // TCP client
            "Networking",     // FInternetAddr / socket helpers
        });

        // Private deps are added per-phase as systems come online. Kept here as
        // commented hints so you can enable them without hunting the docs:
        PrivateDependencyModuleNames.AddRange(new string[]
        {
            "Water",           // hydrostatics: WaterBody surface sampling (KI-022 port)
            // "Niagara",      // Phase 11 — wake / spray VFX
            "UMG", "Slate", "SlateCore",      // Phase 10 — HUD (WP_20260701 bridge dashboard)
            // "CesiumRuntime",               // Phase 6 — GPS lat/lon via georeference
        });

        // NaviSense compiles clean; treat warnings seriously from day one.
        bEnableExceptions = false;
    }
}
